<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Learnfy.Data/Learnfy.Data.csproj" />
    <ProjectReference Include="../Learnfy.Migrations.SqlServer/Learnfy.Migrations.SqlServer.csproj" />
    <ProjectReference Include="../Learnfy.Migrations.Sqlite/Learnfy.Migrations.Sqlite.csproj" />
  </ItemGroup>
</Project>
